const fs = require('fs');
const path = require('path');
const kleur = require('kleur');

console.log(kleur.cyan('🐳 Shadow OPS: Dockerizing...'));

const rootDir = process.cwd();

// Detect Stack
let stackType = 'node';
if (fs.existsSync(path.join(rootDir, 'requirements.txt'))) {
    stackType = 'python';
}

console.log(kleur.dim(`> Detected Stack: ${stackType.toUpperCase()}`));

const dockerfileNode = `
# 🐳 AUTO-GENERATED BY SHADOW GRAVITY
FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build
EXPOSE 3000

CMD ["npm", "start"]
`;

const dockerfilePython = `
# 🐳 AUTO-GENERATED BY SHADOW GRAVITY
FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000
CMD ["python", "main.py"]
`;

const dockerCompose = `
version: '3.8'
services:
  app:
    build: .
    ports:
      - "${stackType === 'python' ? '8000:8000' : '3000:3000'}"
    environment:
      - NODE_ENV=production
`;

const dockerContent = stackType === 'python' ? dockerfilePython : dockerfileNode;

// Write Files
try {
    fs.writeFileSync(path.join(rootDir, 'Dockerfile'), dockerContent.trim());
    console.log(kleur.green('✅ Dockerfile created.'));

    fs.writeFileSync(path.join(rootDir, 'docker-compose.yml'), dockerCompose.trim());
    console.log(kleur.green('✅ docker-compose.yml created.'));
} catch (e) {
    console.log(kleur.red(`❌ Failed to write Docker files: ${e.message}`));
}
